[project]
name = "ty-vscode"
version = "2025.74.0"
requires-python = ">=3.8"
dependencies = ["ty==0.0.3"]

[tool.ruff]
line-length = 88
target-version = "py37"

[tool.ruff.lint]
select = ["E", "F", "W", "Q", "UP", "I", "N"]
